language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - touch assets/vmlinux
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
