language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - $TRAVIS_BUILD_DIR/assets
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - cd assets
  - wget -N https://storage.googleapis.com/firesquid/vmlinux
  - wget -N https://storage.googleapis.com/firesquid/rootfs.ext4
  - wget -N https://github.com/firecracker-microvm/firecracker/releases/download/v0.22.0/firecracker-v0.22.0-x86_64
  - cp firecracker-v0.22.0-x86_64 firecracker
  - cd ..
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
after_script:
  - rm assets/firecracker
