[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
name = "firesquid"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
clap = { version = "2.33.3", features = ["yaml"] }
hyper = { version = "0.14.4", features = ["client", "server", "stream", "http1", "tcp"] }
hyperlocal = { version = "0.8" }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.63"
tokio = { version = "1.2.0", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
    "net",
] }
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
