[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
name = "firesquid"
version = "0.1.0"

[dependencies]
clap = {version = "2.33.3", features = ['yaml']}
hyper = {version = "0.13.8", features = ["stream"]}
hyperlocal = "0.7"
serde = {version = "1.0.116", features = ["derive"]}
serde_json = "1.0.57"
tokio = {version = "0.2.22", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.2"
