[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
name = "firesquid"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
clap = { version = "2.33.3", features = ['yaml'] }
hyper = { version = '0.14.1', features = ["client", "server", "stream", 'http1', 'tcp'] }
hyperlocal = { path = '../hyperlocal' }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1.0.0", features = [
    'fs',
    'io-util',
    'macros',
    'process',
    'rt-multi-thread',
    'signal',
    'sync',
    'time',
    'net',
] }
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
