CREATE TABLE vms (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    last_error TEXT,
    kernel_path TEXT NOT NULL DEFAULT '',
    rootfs_path TEXT NOT NULL DEFAULT '',
    vcpus INTEGER NOT NULL DEFAULT 1,
    memory_mib INTEGER NOT NULL DEFAULT 512,
    pid INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vm_id TEXT,
    event TEXT NOT NULL,
    detail TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
