[package]
edition = "2021"
name = "unix-client"
version = "0.1.0"


[dependencies]
bytes = "1.5.0"
http-body-util = "0.1.0"
hyper = { version = "1.0.1", features = ["client", "http1"] }
pin-project-lite = "0.2.13"
tokio = { version = "1.35", features = ["time", "rt", "net"] }
