name: Branches

on:
  push:
    branches-ignore: 
     - 'main'

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo check
        run: cargo check --verbose
      
      - name: Cargo Build
        run: cargo build --verbose
