name: Branches

on:
  push:
    branches-ignore: 
     - 'main'

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: cd assets
      - run: wget -N https://storage.googleapis.com/firesquid/vmlinux
      - run: wget -N https://storage.googleapis.com/firesquid/rootfs.ext4
      - run: wget -N https://github.com/firecracker-microvm/firecracker/releases/download/v0.22.0/firecracker-v0.22.0-x86_64
      - run: mv firecracker-v0.22.0-x86_64 firecracker
      - run: cd ..

      - name: Cargo check
        run: cargo check --verbose
      
      - name: Cargo Build
        run: cargo build --verbose
