name: Branches

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - "release-please-*"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        name: installing toolchain
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.2

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: check
        run: cargo check --workspace

      - name: test
        run: cargo test --workspace

      - name: build
        run: cargo build --workspace --release
