name: Main

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: Installing Rust Toolchain
        with:
          profile: default
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.1

      - uses: actions-rs/cargo@v1
        name: Cargo Fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Cargo Clippy
        with:
          command: clippy
          args: --release -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Cargo Build
        with:
          command: build
          args: --release

      - uses: google-github-actions/release-please-action@v4
        name: Release
        id: release
        with:
          release-type: rust
          package-name: firesquid

      - name: Get assets
        if: ${{ steps.release.outputs.release_created }}
        run: curl -fsSL https://raw.githubusercontent.com/sousandrei/firesquid/main/scripts/getassets.sh | sh

      - uses: actions-rs/cargo@v1
        if: ${{ steps.release.outputs.release_created }}
        name: Install Cargo Deb
        with:
          command: install
          args: cargo-deb

      - uses: actions-rs/cargo@v1
        if: ${{ steps.release.outputs.release_created }}
        name: Build Debian Package
        with:
          command: deb

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./target/debian/*.deb
