name: Main

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        name: Installing Rust Toolchain
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Cargo Fmt
        run: cargo fmt --all -- --check

      - name: Cargo Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Cargo Check
        run: cargo check --workspace

      - name: Cargo Test
        run: cargo test --workspace

      - name: Cargo Build
        run: cargo build --workspace --release

      - uses: google-github-actions/release-please-action@v4
        name: Release
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: taiki-e/install-action@cargo-deb
        if: ${{ steps.release.outputs.release_created }}
        name: Install Cargo Deb

      - name: Build Debian Package
        if: ${{ steps.release.outputs.release_created }}
        run: cargo deb

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./target/debian/*.deb
