name: Main

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: Installing Rust Toolchain
        with:
          profile: default
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.6.0

      - uses: actions-rs/cargo@v1
        name: Cargo Fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Cargo Clippy
        with:
          command: clippy
          args: --release -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Cargo Build
        with:
          command: build
          args: --release

      - uses: google-github-actions/release-please-action@v3
        name: Release
        id: release
        with:
          release-type: rust
          package-name: firesquid
